[package]
name         = "fuzzy"
version      = "0.1.0"
authors      = ["jmaargh <https://github.com/jmaargh>", "museun <https://github.com/museun"]
license-file = "LICENSE"
edition      = "2021"

[dependencies]
ndarray   = "0.15.6"
